import type { Metadata } from "next";
import "./globals.css";
import Navigation from "@/components/Navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className="bg-gray-g2 m-0 p-0 flex justify-center">
        <div className="flex flex-col w-full max-w-[480px] min-h-screen bg-white shadow-md overflow-hidden">
          <div className="flex-1 overflow-y-auto px-4">{children}</div>
          <Navigation />
        </div>
      </body>
    </html>
  );
}
